### ISSUE TITLE
玩家的业务处理线程

### ISSUE THREAD

**Issue by likeAwind** [xhxPanda/mmorpg-xiehongxin#1]
public class CMDmanager {

	public static final CMDmanager INSTANCE = new CMDmanager();

	public void dealCMD(CMDdomain cmddomain) {
		// 获取模块
		String cmd = cmddomain.getStringParam(0);
		if (cmd.equals("doLogin") || cmd.equals("doRegister")) {
			UserService.INSTANCE.doLoginOrRegister(cmddomain);
		} else {
			Integer userId = cmddomain.getIntParam(1);
			if (userId != null) {
				User user = UserService.INSTANCE.getUser(userId);
				if (user == null) {
					ExtensionSender.INSTANCE.sendReply(cmddomain.getChannel(), ReplyDomain.FAILE);
				}
				CmdHandlerMananger.INSATANCE.invokeHandler(user, cmddomain);
			}
		}
	}

}

玩家的消息是直接在 netty的IO线程里面处理？
如何确保IO线程不会被阻塞?

**Comment by likeAwind** [comment]
CMDmanager 这个类名 是不是不太符合JAVA的驼峰命名规范？类似的问题项目里面还有很多！

**Comment by xhxPanda** [comment]
命名规范这个我已经改了，如果我在后面优化的过程中还发现有的话一定会去修改

**Comment by xhxPanda** [comment]
我想请教一个事，就是我是使用定时线程池还是使用别的线程池去实现业务线程异步，还是使用threadfactory生成固定的几个线程去完成这个功能？

**Comment by xhxPanda** [comment]
'''
	private ExecutorService executorService;

	private CmdManager() {
		executorService = Executors.newFixedThreadPool(5);
	}

	/**
	 * 每一个命令传进来都放到线程池中运行保证不会堵塞nettyIo
	 * 
	 * @param cmdDomain
	 */
	public void dealCMD(CmdDomain cmdDomain) {

		executorService.execute(new Runnable() {
			@Override
			public void run() {
				String cmd = cmdDomain.getStringParam(0);
				if (cmd.equals("doLogin") || cmd.equals("doRegister")) {
					UserService.INSTANCE.doLoginOrRegister(cmdDomain);
				} else {
					Integer userId = cmdDomain.getIntParam(1);
					if (userId != null) {
						User user = UserService.INSTANCE.getUser(userId);
						if (user == null) {
							ExtensionSender.INSTANCE.sendReply(cmdDomain.getChannel(), ReplyDomain.FAILE);
						}
						CmdHandlerMananger.INSATANCE.invokeHandler(user, cmdDomain);
					}
				}
			}
		});
	}'''
在用户请求进来的时候我会开一个线程扔进线程池中运行

**Comment by likeAwind** [comment]
这样做，或许IO线程不会被阻塞了，但其它线程也可能会被阻塞。
而且它又会带来另外一些问题，再线程池中玩家的业务是会被并发执行的。例如玩家先发起一个 整理背包 相对来说比较耗时的操作。然后又突然发起消耗物品类操作。这两个操作可能会同时执行。这种问题在玩家的各个模块都有可能出现 如何避免？
@xhxPanda

**Comment by xhxPanda** [comment]
我借鉴了黄超的实现方式，结合我自己的项目现状，调整成每个用户都有自己的一个线程队列，在userService里面定时把用户队列中的命令放到线程池中执行，这样既可以保证线程不会相互影响，也能保证命令的有序执行

**Comment by likeAwind** [comment]
@xhxPanda 
private CmdManager() {
		executorService = Executors.newFixedThreadPool(6);
	}

public class User {

	private int userId;
	private String name;
	private String password;
	private Channel channel;

	// 包
	private BlockingQueue<Runnable> cmdDomains;

	public User(int userId, String name, String password) {
		this.password = password;
		this.userId = userId;
		this.name = name;

		cmdDomains = new LinkedBlockingQueue<>();
	}


你把这个6改成2. 然后登陆3个账号试一试 会不会有问题？

**Comment by xhxPanda** [comment]
哦，对，那用CachedThreadPool

**Comment by xhxPanda** [comment]
![image](https://user-images.githubusercontent.com/17882183/50147885-1c33aa80-02f2-11e9-8796-2d736347dd84.png)

就我在网上看到有这样的一种线程模型，好像不太优雅，但是似乎能贴近你所说的要求，请你指点指点

**Comment by likeAwind** [comment]
@xhxPanda 
其实黄超的方法也可以，因为他并没有使用阻塞队列。
方法很多，但最终的目的是使得玩家的业务消息将会有序的执行。这样可以简单高效的避免玩家自身的并发问题。但这个并不能解决公共系统的并发问题。至于游戏里面有哪些业务是公共系统，需要单独处理并发的可以找 @suhaijin 那个issues里面详细讨论。
同时这种模型，是非常怕有阻塞操作的。请自行总结业务中哪些地方可能会出现阻塞。这种阻塞是否可以避免，并且评估阻塞的时间会有多长？

**Comment by suhaijin** [comment]
怎么说呢，并发这个技术问题，简直可以开个课程讨论了。它没有特定的方案解决所有并发问题，只能说针对不同的问题有不同的并发处理策略。比如说，针对io与业务分离，我们可以以玩家为节点---比如可以按玩家分配线程池中的线程，当然也有其他方式，例如以场景为节点（甚至有些大型把某些大型场景做成单独服务的），这些都是解决mmo的并发问题的。再比如，多人交互的组队，公会等，既可以用简单粗暴的模块中一把大锁搞定 ，也可以分离业务针对的使用线程池，各种方式的优劣在不同的并发量级下也是不同的。
具体使用什么方案处理并发，需要看我们游戏模块的适用场景，以及模块中并发的量与竞争度。
总之一句话：并发问题的处理方式，都是依赖于并发量与竞争激烈度。真的没有万能通用的处理方式，也没有最好。
所以，特定问题，咱们具体讨论。
你可以把你写的这些各种关于并发的问题，一一总结记录下来，找时间咱们一个一个线下面对面交流吧，敲字真的不合适。
以上简单说到的那些小细节点，你也可以自己先考虑考虑，想想他们的可行性和优缺点。
