### ISSUE TITLE
// TODO Auto-generated method stub

### ISSUE THREAD

**Issue by likeAwind** [xhxPanda/mmorpg-xiehongxin#2]
![image](https://user-images.githubusercontent.com/11746765/49862242-b5694980-fe38-11e8-885f-d13c38a07070.png)
这些莫名其妙的 TODO 是什么？

**Comment by xhxPanda** [comment]
这是eclipse自动生成的一个东西，我会修正的，我想请问，在实际开发过程中，这些自动生成的东西是不是不要有？

**Comment by likeAwind** [comment]
TODO 这个标识的含义是什么？

**Comment by xhxPanda** [comment]
我个人认为这标识没啥含义，就是一个eclipse的生成模版，我已经把所有代码上的这个东西删掉了，然后设置生成代码模版的时候不生成这个标识

**Comment by likeAwind** [comment]
TODO: + 说明：
如果代码中有该标识，说明在标识处有功能代码待编写，待实现的功能在说明中会简略说明。

FIXME: + 说明：
如果代码中有该标识，说明标识处代码需要修正，甚至代码是错误的，不能工作，需要修复，如何修正会在说明中简略说明。

XXX: + 说明：
如果代码中有该标识，说明标识处代码虽然实现了功能，但是实现的方法有待商榷，希望将来能改进，要改进的地方会在说明中简略说明。

**Comment by xhxPanda** [comment]
哦哦，因此如果功能完成并测试通过以后的话就需要把该标识删掉
