### ISSUE TITLE
事件处理接口的参数固定，可以直接用接口调用的方式，不需要使用到反射

### ISSUE THREAD

**Issue by wlong36** [xhxPanda/mmorpg-xiehongxin#3]
https://github.com/xhxPanda/mmorpg-xiehongxin/blob/6d4c25ea985a8af3d539e4ad759e9e7dd7fa6b20/src/main/java/com/hh/mmorpg/event/EventHandler.java#L6

反射存在性能损耗，不是特殊情况，尽量不使用反射
事件处理接口的参数是固定的 EventData，可以直接采用多态的方式处理，在服务器启动的时候注册事件处理器，事件产生后批量抛出事件

**Comment by xhxPanda** [comment]
@fruitbear 
对于反射对性能损耗这个问题我听到过两种人的说法，第一种人觉得反射的损耗是可以忽略不计，在系统中有规范的东西都使用反射，另外一种就是像您一样的看法。所以我想问到底反射在生产环境下系统中性能的消耗的衡量应该是怎样的呢？
对于这个问题本身，就写完这个系统的事件机制之后我有点沾沾自喜觉得自己写了点不一样的东西出来，然后我重新思考与衡量之后，发现我的思维被反射这机制给限制住了，所以我有点想不出怎样使用多态然后拋事件。

**Comment by wlong36** [comment]
使用事件机制来解耦各个模块，是一种很好的做法，是服务器开发过程中常用的，没问题
性能影响的问题，听再多人说，不如自己动手测试
至于怎样不使用反射的方式，你可以再思考一下

**Comment by xhxPanda** [comment]
而且如果我的事件机制是异步的而不是同步的会不会对性能的损耗没那么大呢

**Comment by xhxPanda** [comment]
@fruitbear 
我实在想不出不用反射的方式去处理这个问题，请您指教一下，虽然我知道传入的都是同样的参数，但是每个地方业务里面的处理是不一样的?

而且如果我的事件机制是异步的而不是同步的会不会对性能的损耗没那么大呢

**Comment by wlong36** [comment]
反射，我个人感觉主要是用来解决抽象模型下，公共接口参数不固定的情况，而不是作为常规开发手段
而你的这个事件体系，是可以很好的用抽象模型解决的
采用接口+泛型 EventHandler<E extends AbstractEvent>  就能解决你的问题，这样参数明确，还有强类型约束

**Comment by xhxPanda** [comment]
我已经改了
这是EventHandler:
'
public class EventHandler {

	public static final EventHandler INSTANCE = new EventHandler();

	private Map<Integer, List<EventBuilder>> eventBuilds;

	private EventHandler() {
		eventBuilds = new HashMap<>();
	}

	public void addHandler(int type, EventBuilder eventBuild) {
		List<EventBuilder> builds = (List<EventBuilder>) eventBuilds.get(type);

		if (builds == null) {
			builds = new ArrayList<>();
			eventBuilds.put(type, builds);
		}

		builds.add(eventBuild);
	}

	public void invodeMethod(int type, EventData eventData) {
		List<EventBuilder> builds = (List<EventBuilder>) eventBuilds.get(type);

		for (EventBuilder eventBuilder : builds) {
			eventBuilder.handler(eventData);
		}
	}

}'

这是注册事件的方法：
'// 注册事件
		EventHandler.INSTANCE.addHandler(EventType.USER_LOST, userLostEvent);'''

这是其中的一个业务逻辑：
'
	private EventBuilder<UserLostData> userLostEvent = new EventBuilder<UserLostData>() {

		@Override
		public void handler(UserLostData userLostData) {
			int userId = userLostData.getUser().getUserId();

			System.out.println("userId为：" + userId + "的用户下线了");
		}
	};'

你觉得这样的方式去做会好一点吗，其实我之前自己封装jdbc的时候也用到类似的逻辑来做
@fruitbear

**Comment by xhxPanda** [comment]
![image](https://user-images.githubusercontent.com/17882183/50132067-2472f200-02c0-11e9-964a-0579465d31ba.png)

引入一个新的问题啊，如果我用这样的方式去写代码的话，EventHandler里面将会有一堆的警告信息，怎样可以优化一下呢，我想了挺久都没想到方案

**Comment by wlong36** [comment]
这里涉及到的泛型的使用方式，你可以查阅一下java泛型的相关资料
在这部分里面，EventBuilder的泛型参数，主要是为了将事件类型传递到事件处理类中去，不用事件处理的地方再次进行强转。

你图中这么多警告，是因为你的代码抹除了泛型参数，会导致失去强类型检测的功能，无法及时发现参数传入错误

**Comment by xhxPanda** [comment]
那是不是下面那个invodeMethod的方法可以改一种写法，但是我不知道怎么写才不会报错或者是没有警告
