### ISSUE TITLE
汉字信息，国际化问题

### ISSUE THREAD

**Issue by likeAwind** [xhxPanda/mmorpg-xiehongxin#5]
![image](https://user-images.githubusercontent.com/11746765/49862657-9fa85400-fe39-11e8-8fe6-906840482985.png)
这些发送给客户端显示的文字 是否应该封装到配置文件里面？ 一个是策划修改方便 一个是方便以后国际化

**Comment by xhxPanda** [comment]
这个问题我已经改进了，所有返回前端的信息我都使用了配置文件进行管理
