### ISSUE TITLE
Increment问题

### ISSUE THREAD

**Issue by likeAwind** [xhxPanda/mmorpg-xiehongxin#6]
这个包的命名是怎么回事？
还有这个increment是做什么用的，意义不明？为何完全没有注释，这个问题在项目的其它地方是否也随处可见？

**Comment by likeAwind** [comment]
![image](https://user-images.githubusercontent.com/11746765/49862999-51478500-fe3a-11e8-9ff8-f014e478ac12.png)

**Comment by xhxPanda** [comment]
这个类的作用是生成全局唯一id的，我没有对其进行注释是我的疏忽，在写代码的时候我会随时检测是否有同样的问题存在
