### ISSUE TITLE
数据库操作为同步操作，会带来严重的性能问题

### ISSUE THREAD

**Issue by wlong36** [xhxPanda/mmorpg-xiehongxin#7]
业务执行完成后，会同步调用jdbc代码进行数据的insert与update，数据库操作的延迟一般在10ms以上，会严重阻塞业务线程，建议采用异步入库的方式处理

**Comment by xhxPanda** [comment]
@fruitbear 

谢谢您的反馈，面对这样的问题我之前也有考虑过，我想了两种方案做处理，我不知道在生产环境中是使用的哪种方案，请您指教：
方案1：一开始把所有的数据加载到内存当中（其实我现在也是这样做的），然后使用钩子，在jvm关闭的时候把数据刷回去
方案2：使用线程池做一个异步读写数据库的处理。

**Comment by wlong36** [comment]
方案1：
所有数据加载到内存，对内存来说是不必要的浪费，实际内存中只需要保持热点数据就可以；
钩子刷数据有点多此一举，1是刷数据报错，在钩子这个线程中已经不好做回滚重试等操作了，2是一旦服务器出现宕机等严重问题，回档无法预估

方案2：
目前服务器大多采用这种方案，可以尝试做一下

**Comment by xhxPanda** [comment]
```private void dealSqlIntoDb() {
		if (blockingQueue.isEmpty()) {
			return;
		}
		try {
			SqlExcutor sqlExcutor = blockingQueue.take();
			PreparedStatement pstmt;
			try {
				pstmt = (PreparedStatement) conn.prepareStatement(sqlExcutor.getSql());
				Object[] objects = sqlExcutor.getObjects();
				for (int i = 0; i < objects.length; i++) {
					pstmt.setObject(i + 1, objects[i]);
				}

				pstmt.executeUpdate();
			} catch (SQLException e) {

				e.printStackTrace();
			}
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
	}```

**Comment by xhxPanda** [comment]
我用了定时线程池去处理这个问题，实现了异步更新数据

**Comment by wlong36** [comment]
思路是没问题的，很好
还有一些可以优化的点
这里可以观察一下存储队列中的数据都有哪些特征，针对这些特征可以做哪些优化处理
另一点是，玩家数据的安全性是很重要的，在入库存储的时候如果出现异常，是需要特别注意处理的

**Comment by xhxPanda** [comment]
你说的最后一点也是我周末的时候想到要请教你的，在线程池中加入怎样的机制可以比较好的处理入库的时候出现的异常。因为有很多的异常未必能捕获得到，出了错也许都没有报错信息出现

**Comment by wlong36** [comment]
1. 业务代码的调用，可以自己封装一层，来加入异常捕获处理代码
2. 开发业务的过程中，要多想想出现异常的可能性，思考为什么会出现，出现了应该怎么处理，处理方式是视业务逻辑而定的

**Comment by xhxPanda** [comment]
![image](https://user-images.githubusercontent.com/17882183/50153719-35445780-0302-11e9-9f1f-85b79c77592b.png)
是这样的，这一段代码是让线程池去定时执行入库执行sql语句，在catch那里可以加入异常的处理，比如写个日志或者是报警之类的，这样应该可以（对于这个小项目），就我想请教在生产环境下，除了sql语句写错了、数据库撑爆了之类的数据库错误以外，我们还需要留意什么

**Comment by wlong36** [comment]
对于数据库缓存数据，要留意以下几个方面
1 脏数据
2 数据落地正确性
3 存储队列阻塞
4 吞吐量

**Comment by xhxPanda** [comment]
虽然我还有点不理解你说的这些名词，但是我试着解释一下吧
1、内存有可能会有脏数据，我用谷歌的那个缓存，自带的lru算法，缓存热点数据。如果没有就从数据库里面重新load嘛,，不过lru算法要保证数据库跟内存中的数据保持一致这个是有点难度的
2、数据落地的正确性，sql不写错，会查log恢复数据
3、队列的堵塞这个问题，我是使用了生产者消费者模式，只有一个缓存队列，那在这个场景下堵塞队列的问题也应当不那么大。
4、吞吐量这个就很复杂了，要提高吞吐量的话应该是不要那么多的读写操作，如果非要有读写操作就要把读写操作分流分时减少对数据库的一个压力。另外一个方面就是可以对队列中的sql进行合并，比如经验增加十分频繁，那我们可以把增加经验的sql合并执行，但是操作上我没有一个比较好的方案。我自己使用的方式就很鸡贼，用户下线的时候才会把数据回写（这种方案很差，因为不能保证用户在过程中服务器会不会宕机），但也不失为一种解决方案
