### ISSUE TITLE
多人交互安全问题

### ISSUE THREAD

**Issue by suhaijin** [xhxPanda/mmorpg-xiehongxin#8]
多人交互系统的线程安全问题。利润组队系统的创建队伍，入队退队等，需要考虑到多线程并发安全。类似此类问题，包括但不限于公会等等。

**Comment by xhxPanda** [comment]
哦，确实，你提出这个问题是我忽视了组队中的多线程并发的问题，我稍后去修改一下

**Comment by xhxPanda** [comment]
其实我在公会、交易、pk都加入了对多线程并发的处理

**Comment by xhxPanda** [comment]
![image](https://user-images.githubusercontent.com/17882183/50155233-89513b00-0306-11e9-9d8d-c4b16830dadd.png)
对了，既然说到了多线程的问题，我对扣血这个操作是做了这样的一个处理，很简单粗暴地上个锁，其实有没有更好的处理方式，或者是你有没有推荐些什么方式去做？

**Comment by xhxPanda** [comment]
![image](https://user-images.githubusercontent.com/17882183/50155421-f795fd80-0306-11e9-8af2-384a081982c9.png)

还有一个问题啊，匡大说我处理业务的线程写得不对，然后我在网上发现了一个线程模型的写法，我知道那个东西并不优雅，但是好像挺接近生产环境的线程模型，我想你能不能给点建议

**Comment by xhxPanda** [comment]
我把线程模型改到了场景上面去处理，利用场景心跳定时执行场景中的所有命令
