### ISSUE TITLE
作为一个有追求的程序员，应该拥有一点代码洁癖

### ISSUE THREAD

**Issue by likeAwind** [xhxPanda/mmorpg-xiehongxin#9]
![image](https://user-images.githubusercontent.com/11746765/50088353-c0a7e500-023d-11e9-99fe-d0a35b5452f7.png)
这种警告（编译器的警告大部分情况下是需要处理的，只有在极少数我们很清楚为什么要忽略的才打上忽略的注解。但不应该无视它们）和多余的转换没有任何意义。只会让代码看起来ugly。
@xhxPanda

**Comment by xhxPanda** [comment]
哦，这个是因为泛型所报的一个警告错误，我做完有点兴奋因为终于想出这个方案没有处理，这个项目里面好像就这个类出了警告的问题，其他的比如引入无意义的包或者是警告我都处理了，我平时也会注意这个问题，不好意思

**Comment by xhxPanda** [comment]
我改了这个问题，连带着把项目里面可以消除wanning的地方也改了，但是有一些确实也没法去，以后我会注意这个问题，改善自己的编码
